import { DashboardStats } from '@/types';
import { 
  Institution, 
  SubscriptionPlan,
  AuditLog,
  countryOptions,
  institutionTypeLabels,
  statusVariants 
} from '@/types/database';

// Re-export for backwards compatibility
export { countryOptions, institutionTypeLabels, statusVariants };

// Mock data for development (will be replaced by real database queries)
export const mockInstitutions: Institution[] = [
  {
    id: '1',
    name: 'Nairobi Academy',
    code: 'NA001',
    type: 'secondary',
    status: 'active',
    subscription_plan: 'professional',
    ownership_type: 'private',
    country: 'KE',
    county: 'Nairobi',
    address: '123 Education Lane, Westlands',
    phone: '+254 712 345 678',
    email: 'admin@nairobiacademy.co.ke',
    website: 'www.nairobiacademy.co.ke',
    logo_url: null,
    student_count: 1250,
    staff_count: 85,
    enabled_modules: ['academics', 'finance', 'communication', 'hr'],
    settings: {},
    curriculum: 'ke_cbc',
    trial_ends_at: null,
    created_at: '2023-06-15T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'Mombasa Technical Institute',
    code: 'MTI002',
    type: 'tvet',
    status: 'active',
    subscription_plan: 'enterprise',
    ownership_type: 'public',
    country: 'KE',
    county: 'Mombasa',
    address: '456 Technical Rd, Nyali',
    phone: '+254 722 987 654',
    email: 'info@mombasatech.ac.ke',
    website: null,
    logo_url: null,
    student_count: 2100,
    staff_count: 120,
    enabled_modules: ['academics', 'finance', 'communication', 'hr', 'inventory'],
    settings: {},
    curriculum: 'ke_cbc',
    trial_ends_at: null,
    created_at: '2023-03-01T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
  },
  {
    id: '3',
    name: 'Kisumu Primary School',
    code: 'KPS003',
    type: 'primary',
    status: 'trial',
    subscription_plan: 'starter',
    ownership_type: 'public',
    country: 'KE',
    county: 'Kisumu',
    address: '789 Lakeside Ave',
    phone: '+254 733 456 789',
    email: 'head@kisumuprimary.sc.ke',
    website: null,
    logo_url: null,
    student_count: 450,
    staff_count: 25,
    enabled_modules: ['academics', 'finance'],
    settings: {},
    curriculum: 'ke_cbc',
    trial_ends_at: '2024-02-02T00:00:00Z',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
  },
  {
    id: '4',
    name: 'Eldoret University College',
    code: 'EUC004',
    type: 'college',
    status: 'active',
    subscription_plan: 'enterprise',
    ownership_type: 'private',
    country: 'KE',
    county: 'Uasin Gishu',
    address: null,
    phone: '+254 744 321 654',
    email: 'registrar@eldoretuc.ac.ke',
    website: 'www.eldoretuc.ac.ke',
    logo_url: null,
    student_count: 5200,
    staff_count: 280,
    enabled_modules: ['academics', 'finance', 'communication', 'hr', 'inventory', 'library'],
    settings: {},
    curriculum: null,
    trial_ends_at: null,
    created_at: '2022-09-01T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
  },
  {
    id: '5',
    name: 'Nakuru Girls High School',
    code: 'NGHS005',
    type: 'secondary',
    status: 'suspended',
    subscription_plan: 'professional',
    ownership_type: 'public',
    country: 'KE',
    county: 'Nakuru',
    address: null,
    phone: '+254 755 654 321',
    email: 'principal@nakurugirls.sc.ke',
    website: null,
    logo_url: null,
    student_count: 890,
    staff_count: 52,
    enabled_modules: ['academics', 'finance', 'communication'],
    settings: {},
    curriculum: 'ke_cbc',
    trial_ends_at: null,
    created_at: '2023-02-15T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Kampala International Academy',
    code: 'KIA006',
    type: 'secondary',
    status: 'pending',
    subscription_plan: 'professional',
    ownership_type: 'private',
    country: 'UG',
    county: null,
    address: 'Plot 45, Kololo Hill',
    phone: '+256 701 234 567',
    email: 'admin@kampalaia.ac.ug',
    website: null,
    logo_url: null,
    student_count: 0,
    staff_count: 0,
    enabled_modules: [],
    settings: {},
    curriculum: null,
    trial_ends_at: null,
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2024-01-14T00:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalInstitutions: 156,
  activeInstitutions: 142,
  totalStudents: 45230,
  totalStaff: 3420,
  monthlyRevenue: 2850000,
  revenueGrowth: 12.5,
  newInstitutionsThisMonth: 8,
  pendingTickets: 23,
};

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Perfect for small schools getting started',
    price_monthly: 5000,
    price_yearly: 48000,
    currency: 'KES',
    max_students: 500,
    max_staff: 50,
    features: ['Basic student management', 'Fee collection', 'SMS notifications', 'Basic reports'],
    modules: ['academics', 'finance'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'For growing institutions with advanced needs',
    price_monthly: 15000,
    price_yearly: 144000,
    currency: 'KES',
    max_students: 2000,
    max_staff: 150,
    features: ['Everything in Starter', 'HR management', 'Advanced analytics', 'WhatsApp integration', 'Custom report builder'],
    modules: ['academics', 'finance', 'communication', 'hr'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Full-featured solution for large institutions',
    price_monthly: 35000,
    price_yearly: 336000,
    currency: 'KES',
    max_students: 10000,
    max_staff: 500,
    features: ['Everything in Professional', 'Multi-campus support', 'API access', 'Dedicated support', 'Custom integrations', 'White-labeling'],
    modules: ['academics', 'finance', 'communication', 'hr', 'inventory', 'library', 'transport'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'custom',
    name: 'Custom',
    description: 'Tailored solutions for unique requirements',
    price_monthly: 0,
    price_yearly: 0,
    currency: 'KES',
    max_students: -1,
    max_staff: -1,
    features: ['Fully customizable', 'Dedicated infrastructure', 'On-premise option', '24/7 priority support', 'Custom development'],
    modules: ['all'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    user_id: 'user-1',
    user_email: 'admin@zira.tech',
    action: 'institution.created',
    entity_type: 'institution',
    entity_id: '6',
    institution_id: null,
    metadata: { institutionName: 'Kampala International Academy' },
    ip_address: '41.90.123.45',
    permission_used: null,
    old_values: null,
    new_values: null,
    request_id: null,
    user_agent: null,
    created_at: '2024-01-14T10:30:00Z',
  },
  {
    id: '2',
    user_id: 'user-1',
    user_email: 'admin@zira.tech',
    action: 'institution.suspended',
    entity_type: 'institution',
    entity_id: '5',
    institution_id: null,
    metadata: { reason: 'Payment overdue' },
    ip_address: '41.90.123.45',
    permission_used: null,
    old_values: null,
    new_values: null,
    request_id: null,
    user_agent: null,
    created_at: '2024-01-14T09:15:00Z',
  },
  {
    id: '3',
    user_id: 'user-2',
    user_email: 'support@zira.tech',
    action: 'subscription.upgraded',
    entity_type: 'institution',
    entity_id: '2',
    institution_id: null,
    metadata: { fromPlan: 'professional', toPlan: 'enterprise' },
    ip_address: '41.90.124.78',
    permission_used: null,
    old_values: null,
    new_values: null,
    request_id: null,
    user_agent: null,
    created_at: '2024-01-13T14:22:00Z',
  },
];
