import { useState } from 'react';
import { PortalLayout } from '@/components/portal/PortalLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';
import { 
  Plus, FileText, Eye, Trash2, GripVertical, Copy, Wand2, 
  LayoutTemplate, ChevronRight, Download 
} from 'lucide-react';
import { useExamPapers, useCreateExamPaper, useExamPaper, useAddQuestionToPaper, useRemoveQuestionFromPaper } from '@/hooks/useExamPapers';
import { useQuestions } from '@/hooks/useQuestionBank';
import { useSubjects } from '@/hooks/useSubjects';
import { useExams } from '@/hooks/useExams';
import { useInstitution } from '@/contexts/InstitutionContext';
import { useStaffProfile } from '@/hooks/useStaffProfile';
import { useCloneExamPaper } from '@/hooks/useCloneExamPaper';
import { ExamPaperTemplateSelector } from '@/components/exam-paper/ExamPaperTemplateSelector';
import { AutoGenerateDialog } from '@/components/exam-paper/AutoGenerateDialog';
import { ExamPaperPreviewDialog } from '@/components/exam-paper/ExamPaperPreviewDialog';
import { EXAM_PAPER_TEMPLATES, ExamPaperTemplate, ExamPaperSection } from '@/types/question-bank';
import { toast } from 'sonner';

export default function ExamPaperBuilder() {
  const { institution } = useInstitution();
  const { data: profile } = useStaffProfile();
  
  // Dialog states
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showBuilderDialog, setShowBuilderDialog] = useState(false);
  const [showCloneDialog, setShowCloneDialog] = useState(false);
  const [showAutoGenerate, setShowAutoGenerate] = useState(false);
  
  // Selected paper for builder/clone
  const [selectedPaperId, setSelectedPaperId] = useState<string | null>(null);
  const [cloneTargetPaperId, setCloneTargetPaperId] = useState<string | null>(null);
  const [cloneTitle, setCloneTitle] = useState('');
  const [cloneExamId, setCloneExamId] = useState('');
  const [showPreviewDialog, setShowPreviewDialog] = useState(false);
  const [cardPreviewPaperId, setCardPreviewPaperId] = useState<string | null>(null);

  // Create form state
  const [step, setStep] = useState<'template' | 'details'>('template');
  const [selectedTemplate, setSelectedTemplate] = useState<ExamPaperTemplate | null>(null);
  const [formData, setFormData] = useState({
    exam_id: '',
    subject_id: '',
    title: '',
    instructions: '',
    duration_minutes: 120,
    total_marks: 100,
    sections: [{ name: 'Section A', instructions: 'Answer all questions', marks: 100 }] as ExamPaperSection[],
  });

  // Queries and mutations
  const { data: papers = [], isLoading } = useExamPapers();
  const { data: subjects = [] } = useSubjects(institution?.id || null);
  const { data: exams = [] } = useExams(institution?.id || null);
  const { data: questions = [] } = useQuestions({ isActive: true });
  const createPaper = useCreateExamPaper();
  const addQuestion = useAddQuestionToPaper();
  const removeQuestion = useRemoveQuestionFromPaper();
  const clonePaper = useCloneExamPaper();

  const { data: selectedPaper } = useExamPaper(selectedPaperId || '');
  const { data: cardPreviewPaper } = useExamPaper(cardPreviewPaperId || '');

  // Template selection handler
  const handleTemplateSelect = (template: ExamPaperTemplate) => {
    setSelectedTemplate(template);
    setFormData((prev) => ({
      ...prev,
      duration_minutes: template.durationMinutes,
      total_marks: template.totalMarks,
      sections: template.sections.map((s) => ({
        name: s.name,
        instructions: s.instructions,
        marks: s.marks,
      })),
    }));
  };

  // Create paper handler
  const handleCreate = async () => {
    if (!institution?.id || !profile?.id) return;

    const newPaper = await createPaper.mutateAsync({
      institution_id: institution.id,
      exam_id: formData.exam_id,
      subject_id: formData.subject_id,
      title: formData.title,
      instructions: formData.instructions,
      duration_minutes: formData.duration_minutes,
      total_marks: formData.total_marks,
      sections: formData.sections,
      status: 'draft',
      created_by: profile.id,
    });

    setShowCreateDialog(false);
    resetCreateForm();
    setSelectedPaperId(newPaper.id);
    setShowBuilderDialog(true);
  };

  const resetCreateForm = () => {
    setStep('template');
    setSelectedTemplate(null);
    setFormData({
      exam_id: '',
      subject_id: '',
      title: '',
      instructions: '',
      duration_minutes: 120,
      total_marks: 100,
      sections: [{ name: 'Section A', instructions: 'Answer all questions', marks: 100 }],
    });
  };

  const openBuilder = (paperId: string) => {
    setSelectedPaperId(paperId);
    setShowBuilderDialog(true);
  };

  const openCloneDialog = (paperId: string, currentTitle: string) => {
    setCloneTargetPaperId(paperId);
    setCloneTitle(`${currentTitle} (Copy)`);
    setCloneExamId('');
    setShowCloneDialog(true);
  };

  const handleClone = async () => {
    if (!cloneTargetPaperId || !institution?.id || !profile?.id || !cloneTitle) return;

    await clonePaper.mutateAsync({
      paperId: cloneTargetPaperId,
      newTitle: cloneTitle,
      newExamId: cloneExamId || undefined,
      institutionId: institution.id,
      createdBy: profile.id,
    });

    setShowCloneDialog(false);
    setCloneTargetPaperId(null);
  };

  const handleAddQuestion = async (questionId: string, sectionIndex: number) => {
    if (!selectedPaperId) return;

    const currentQuestions = selectedPaper?.questions || [];
    const sectionQuestions = currentQuestions.filter((q) => q.section_index === sectionIndex);

    await addQuestion.mutateAsync({
      exam_paper_id: selectedPaperId,
      question_id: questionId,
      section_index: sectionIndex,
      question_order: sectionQuestions.length + 1,
    });
  };

  const handleAutoGenerate = async (sectionQuestions: { sectionIndex: number; questionIds: string[] }[]) => {
    if (!selectedPaperId) return;

    for (const section of sectionQuestions) {
      for (let i = 0; i < section.questionIds.length; i++) {
        await addQuestion.mutateAsync({
          exam_paper_id: selectedPaperId,
          question_id: section.questionIds[i],
          section_index: section.sectionIndex,
          question_order: i + 1,
        });
      }
    }

    toast.success(`Added ${sectionQuestions.reduce((sum, s) => sum + s.questionIds.length, 0)} questions`);
  };

  const getStatusBadge = (status: string) => {
    const colors: Record<string, string> = {
      draft: 'bg-yellow-100 text-yellow-800',
      finalized: 'bg-green-100 text-green-800',
      archived: 'bg-gray-100 text-gray-800',
    };
    return <Badge className={colors[status] || 'bg-gray-100'}>{status}</Badge>;
  };

  // Filter questions not yet in paper
  const availableQuestions = selectedPaper
    ? questions.filter((q) => !selectedPaper.questions?.some((pq) => pq.question_id === q.id))
    : questions;

  return (
    <PortalLayout title="Exam Paper Builder" subtitle="Create and manage exam papers from question bank">
      <div className="space-y-4 p-4 md:p-6">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <p className="text-sm text-muted-foreground">
              {papers.length} paper(s) created
            </p>
          </div>
          <Button onClick={() => setShowCreateDialog(true)}>
            <Plus className="h-4 w-4 mr-2" />
            New Paper
          </Button>
        </div>

        {/* Papers List */}
        {isLoading ? (
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <Skeleton key={i} className="h-24 w-full" />
            ))}
          </div>
        ) : papers.length === 0 ? (
          <Card>
            <CardContent className="py-12 text-center">
              <FileText className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
              <h3 className="text-lg font-semibold">No exam papers yet</h3>
              <p className="text-muted-foreground mb-4">Create your first exam paper to get started</p>
              <Button onClick={() => setShowCreateDialog(true)}>
                <LayoutTemplate className="h-4 w-4 mr-2" />
                Create from Template
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {papers.map((paper) => (
              <Card key={paper.id} className="hover:shadow-md transition-shadow">
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-base">{paper.title}</CardTitle>
                    {getStatusBadge(paper.status)}
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2 text-sm">
                    <p className="text-muted-foreground">
                      {paper.subject?.name} • {paper.exam?.name}
                    </p>
                    <div className="flex gap-4 text-muted-foreground">
                      <span>{paper.duration_minutes} min</span>
                      <span>{paper.total_marks} marks</span>
                    </div>
                  </div>
                  <div className="mt-4 flex flex-wrap gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => openBuilder(paper.id)}
                    >
                      <FileText className="h-4 w-4 mr-1" />
                      Edit
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => setCardPreviewPaperId(paper.id)}
                      title="Preview"
                    >
                      <Eye className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => setCardPreviewPaperId(paper.id)}
                      title="Download PDF"
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => openCloneDialog(paper.id, paper.title)}
                      title="Clone"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* Create Dialog - Step-based with Template Selector */}
        <Dialog open={showCreateDialog} onOpenChange={(open) => { setShowCreateDialog(open); if (!open) resetCreateForm(); }}>
          <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <LayoutTemplate className="h-5 w-5" />
                Create Exam Paper
                {step === 'details' && (
                  <Badge variant="secondary" className="ml-2">
                    {selectedTemplate?.label}
                  </Badge>
                )}
              </DialogTitle>
            </DialogHeader>

            <div className="flex-1 overflow-y-auto py-4">
              {step === 'template' ? (
                <ExamPaperTemplateSelector
                  selectedTemplate={selectedTemplate?.id || null}
                  onSelect={handleTemplateSelect}
                />
              ) : (
                <div className="space-y-4">
                  <div>
                    <Label>Exam *</Label>
                    <Select
                      value={formData.exam_id}
                      onValueChange={(v) => setFormData({ ...formData, exam_id: v })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select exam" />
                      </SelectTrigger>
                      <SelectContent>
                        {exams.map((e) => (
                          <SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label>Subject *</Label>
                    <Select
                      value={formData.subject_id}
                      onValueChange={(v) => setFormData({ ...formData, subject_id: v })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select subject" />
                      </SelectTrigger>
                      <SelectContent>
                        {subjects.map((s) => (
                          <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label>Paper Title *</Label>
                    <Input
                      value={formData.title}
                      onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                      placeholder="e.g., Mathematics End Term Exam"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label>Duration (minutes)</Label>
                      <Input
                        type="number"
                        value={formData.duration_minutes}
                        onChange={(e) => setFormData({ ...formData, duration_minutes: parseInt(e.target.value) || 120 })}
                      />
                    </div>
                    <div>
                      <Label>Total Marks</Label>
                      <Input
                        type="number"
                        value={formData.total_marks}
                        onChange={(e) => setFormData({ ...formData, total_marks: parseInt(e.target.value) || 100 })}
                      />
                    </div>
                  </div>

                  <div>
                    <Label>Instructions</Label>
                    <Textarea
                      value={formData.instructions}
                      onChange={(e) => setFormData({ ...formData, instructions: e.target.value })}
                      placeholder="Answer all questions. Time: 2 hours..."
                      rows={3}
                    />
                  </div>

                  {/* Sections Preview */}
                  <div>
                    <Label className="mb-2 block">Sections</Label>
                    <div className="space-y-2">
                      {formData.sections.map((section, i) => (
                        <div key={i} className="flex items-center gap-2 p-2 border rounded-md bg-muted/30">
                          <span className="font-medium text-sm flex-1">{section.name}</span>
                          <Badge variant="outline">{section.marks} marks</Badge>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>

            <DialogFooter>
              {step === 'template' ? (
                <>
                  <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
                    Cancel
                  </Button>
                  <Button
                    onClick={() => setStep('details')}
                    disabled={!selectedTemplate}
                  >
                    Continue
                    <ChevronRight className="h-4 w-4 ml-1" />
                  </Button>
                </>
              ) : (
                <>
                  <Button variant="outline" onClick={() => setStep('template')}>
                    Back
                  </Button>
                  <Button
                    onClick={handleCreate}
                    disabled={!formData.exam_id || !formData.subject_id || !formData.title || createPaper.isPending}
                  >
                    {createPaper.isPending ? 'Creating...' : 'Create & Add Questions'}
                  </Button>
                </>
              )}
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Clone Dialog */}
        <Dialog open={showCloneDialog} onOpenChange={setShowCloneDialog}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Copy className="h-5 w-5" />
                Clone Exam Paper
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div>
                <Label>New Paper Title *</Label>
                <Input
                  value={cloneTitle}
                  onChange={(e) => setCloneTitle(e.target.value)}
                  placeholder="Enter new title"
                />
              </div>
              <div>
                <Label>Link to Different Exam (Optional)</Label>
                <Select value={cloneExamId} onValueChange={setCloneExamId}>
                  <SelectTrigger>
                    <SelectValue placeholder="Keep same exam" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">Keep same exam</SelectItem>
                    {exams.map((e) => (
                      <SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowCloneDialog(false)}>
                Cancel
              </Button>
              <Button
                onClick={handleClone}
                disabled={!cloneTitle || clonePaper.isPending}
              >
                {clonePaper.isPending ? 'Cloning...' : 'Clone Paper'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Builder Dialog */}
        <Dialog open={showBuilderDialog} onOpenChange={setShowBuilderDialog}>
          <DialogContent className="max-w-5xl max-h-[90vh] overflow-hidden flex flex-col">
            <DialogHeader>
              <div className="flex justify-between items-center">
                <DialogTitle>{selectedPaper?.title || 'Exam Paper'}</DialogTitle>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => setShowAutoGenerate(true)}
                  disabled={!selectedPaper?.subject_id}
                >
                  <Wand2 className="h-4 w-4 mr-2" />
                  Auto-Generate
                </Button>
              </div>
            </DialogHeader>
            <div className="flex-1 overflow-y-auto">
              <div className="grid md:grid-cols-2 gap-4 py-4">
                {/* Left: Available Questions */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-semibold mb-3">Available Questions ({availableQuestions.length})</h3>
                  <div className="space-y-2 max-h-[50vh] overflow-y-auto">
                    {availableQuestions.map((q) => (
                      <div key={q.id} className="p-3 border rounded-lg text-sm">
                        <div className="flex justify-between items-start gap-2">
                          <div className="flex-1">
                            <div className="flex gap-2 mb-1">
                              <Badge variant="outline" className="text-xs">{q.subject?.name}</Badge>
                              <Badge variant="secondary" className="text-xs">{q.difficulty}</Badge>
                            </div>
                            <p className="line-clamp-2">{q.question_text}</p>
                          </div>
                          <Button
                            size="sm"
                            onClick={() => handleAddQuestion(q.id, 0)}
                            disabled={addQuestion.isPending}
                          >
                            <Plus className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Right: Paper Questions */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-semibold mb-3">Paper Questions ({selectedPaper?.questions?.length || 0})</h3>
                  <div className="space-y-2 max-h-[50vh] overflow-y-auto">
                    {selectedPaper?.questions?.map((pq, i) => (
                      <div key={pq.id} className="p-3 border rounded-lg text-sm flex items-center gap-2">
                        <GripVertical className="h-4 w-4 text-muted-foreground cursor-grab" />
                        <span className="font-medium w-6">{i + 1}.</span>
                        <p className="flex-1 line-clamp-1">{pq.question?.question_text}</p>
                        <span className="text-muted-foreground">
                          {pq.marks_override || pq.question?.marks}m
                        </span>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-6 w-6"
                          onClick={() => removeQuestion.mutate({
                            paperId: selectedPaperId!,
                            questionId: pq.question_id,
                          })}
                        >
                          <Trash2 className="h-3 w-3 text-destructive" />
                        </Button>
                      </div>
                    ))}
                    {(!selectedPaper?.questions || selectedPaper.questions.length === 0) && (
                      <div className="text-center py-8">
                        <p className="text-muted-foreground mb-2">
                          Add questions from the left panel
                        </p>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setShowAutoGenerate(true)}
                          disabled={!selectedPaper?.subject_id}
                        >
                          <Wand2 className="h-4 w-4 mr-2" />
                          Or Auto-Generate
                        </Button>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowBuilderDialog(false)}>
                Close
              </Button>
              <Button 
                onClick={() => setShowPreviewDialog(true)}
                disabled={!selectedPaper?.questions?.length}
              >
                Preview Paper
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Auto-Generate Dialog */}
        {selectedPaper && (
          <AutoGenerateDialog
            open={showAutoGenerate}
            onOpenChange={setShowAutoGenerate}
            sections={selectedPaper.sections as ExamPaperSection[] || []}
            availableQuestions={availableQuestions}
            subjectId={selectedPaper.subject_id}
            institutionId={institution?.id}
            staffId={profile?.id}
            onGenerate={handleAutoGenerate}
          />
        )}

        {/* Preview Dialog - From Builder */}
        <ExamPaperPreviewDialog
          open={showPreviewDialog}
          onOpenChange={setShowPreviewDialog}
          paper={selectedPaper ? {
            title: selectedPaper.title,
            instructions: selectedPaper.instructions || '',
            duration_minutes: selectedPaper.duration_minutes,
            total_marks: selectedPaper.total_marks,
            sections: selectedPaper.sections as ExamPaperSection[] || [],
            subject: selectedPaper.subject,
            exam: selectedPaper.exam,
            questions: selectedPaper.questions,
          } : null}
        />

        {/* Preview Dialog - From Card */}
        <ExamPaperPreviewDialog
          open={!!cardPreviewPaperId}
          onOpenChange={(open) => !open && setCardPreviewPaperId(null)}
          paper={cardPreviewPaper ? {
            title: cardPreviewPaper.title,
            instructions: cardPreviewPaper.instructions || '',
            duration_minutes: cardPreviewPaper.duration_minutes,
            total_marks: cardPreviewPaper.total_marks,
            sections: cardPreviewPaper.sections as ExamPaperSection[] || [],
            subject: cardPreviewPaper.subject,
            exam: cardPreviewPaper.exam,
            questions: cardPreviewPaper.questions,
          } : null}
        />
      </div>
    </PortalLayout>
  );
}
