-- Add sub-strands for ART, CRE, IRE, MUSIC, PE Grade 7-9

INSERT INTO cbc_sub_strands (strand_id, sub_strand_number, name, specific_learning_outcomes, key_inquiry_questions, core_competencies, values, suggested_lesson_count)
VALUES
  -- ART Grade 7
  ('c9a0263a-7d93-4c81-b7e4-e27cf46f5659', 1, 'Advanced Drawing Techniques', 
   '["Apply shading and perspective", "Use different drawing media", "Create expressive drawings"]'::jsonb,
   '["How do artists create depth in drawings?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 6),
  ('c9a0263a-7d93-4c81-b7e4-e27cf46f5659', 2, 'Painting Styles', 
   '["Explore different painting styles", "Mix and apply colors creatively", "Express ideas through painting"]'::jsonb,
   '["What painting styles exist in art history?"]'::jsonb,
   ARRAY['creativity', 'learning_to_learn']::cbc_competency[],
   ARRAY['love', 'patriotism']::cbc_value[], 5),
  ('71ebcc96-5628-474c-86e9-58200a9f791e', 1, 'Digital Art', 
   '["Use digital art tools", "Create digital illustrations", "Edit and manipulate images"]'::jsonb,
   '["How is technology used in art?"]'::jsonb,
   ARRAY['digital_literacy', 'creativity']::cbc_competency[],
   ARRAY['integrity', 'love']::cbc_value[], 6),
  ('71ebcc96-5628-474c-86e9-58200a9f791e', 2, 'Product Design', 
   '["Apply design thinking", "Create functional designs", "Present design solutions"]'::jsonb,
   '["How do designers solve problems?"]'::jsonb,
   ARRAY['creativity', 'critical_thinking']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 5),
  ('31dda546-578d-4424-b23f-5ec21f5a8a12', 1, 'Sculpture', 
   '["Create 3D artworks", "Use different sculpting materials", "Express ideas in 3D form"]'::jsonb,
   '["How do sculptors create 3D art?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'patriotism']::cbc_value[], 6),
  ('31dda546-578d-4424-b23f-5ec21f5a8a12', 2, 'Traditional Crafts', 
   '["Explore Kenyan craft traditions", "Create traditional craft items", "Appreciate cultural heritage"]'::jsonb,
   '["What traditional crafts define our culture?"]'::jsonb,
   ARRAY['creativity', 'citizenship']::cbc_competency[],
   ARRAY['patriotism', 'unity']::cbc_value[], 5),

  -- ART Grade 8
  ('a11607c3-b662-4f5f-839f-c40156c800ab', 1, 'Portrait and Figure Drawing', 
   '["Draw human proportions accurately", "Capture expressions and emotions", "Use different techniques for portraits"]'::jsonb,
   '["How do artists capture human likeness?"]'::jsonb,
   ARRAY['creativity', 'learning_to_learn']::cbc_competency[],
   ARRAY['love', 'respect']::cbc_value[], 6),
  ('a11607c3-b662-4f5f-839f-c40156c800ab', 2, 'Abstract Art', 
   '["Understand abstract art principles", "Create abstract compositions", "Express emotions through abstraction"]'::jsonb,
   '["What is abstract art?"]'::jsonb,
   ARRAY['creativity', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('8b35b453-720e-4b99-8aab-20a3c58192de', 1, 'Graphic Design', 
   '["Apply graphic design principles", "Create visual communications", "Use typography effectively"]'::jsonb,
   '["How do designers communicate visually?"]'::jsonb,
   ARRAY['digital_literacy', 'creativity']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 6),
  ('8b35b453-720e-4b99-8aab-20a3c58192de', 2, 'Interior Design Basics', 
   '["Understand space planning", "Apply color in interiors", "Create design mood boards"]'::jsonb,
   '["How do we design functional spaces?"]'::jsonb,
   ARRAY['creativity', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('3fa60bec-8e2b-413d-975a-2b08fe01a59d', 1, 'Ceramics', 
   '["Work with clay", "Apply pottery techniques", "Create functional and decorative ceramics"]'::jsonb,
   '["How is pottery created?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'patriotism']::cbc_value[], 6),
  ('3fa60bec-8e2b-413d-975a-2b08fe01a59d', 2, 'Textile Arts', 
   '["Create textile artworks", "Apply dyeing and printing techniques", "Design fabric patterns"]'::jsonb,
   '["How are textiles used as art?"]'::jsonb,
   ARRAY['creativity', 'learning_to_learn']::cbc_competency[],
   ARRAY['patriotism', 'love']::cbc_value[], 5),

  -- ART Grade 9
  ('72ba4286-9695-4ca1-82ed-8b259f403944', 1, 'Art History and Appreciation', 
   '["Study major art movements", "Analyze artworks critically", "Connect art to cultural contexts"]'::jsonb,
   '["How has art evolved through history?"]'::jsonb,
   ARRAY['learning_to_learn', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'patriotism']::cbc_value[], 6),
  ('72ba4286-9695-4ca1-82ed-8b259f403944', 2, 'Mixed Media', 
   '["Combine different art materials", "Create mixed media artworks", "Experiment with techniques"]'::jsonb,
   '["How can we combine materials in art?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('744273e3-455f-485b-933d-ee819185225f', 1, 'Animation Basics', 
   '["Understand animation principles", "Create simple animations", "Use animation software"]'::jsonb,
   '["How are animations created?"]'::jsonb,
   ARRAY['digital_literacy', 'creativity']::cbc_competency[],
   ARRAY['love', 'responsibility']::cbc_value[], 6),
  ('744273e3-455f-485b-933d-ee819185225f', 2, 'Photography', 
   '["Apply photography techniques", "Compose effective photographs", "Edit digital images"]'::jsonb,
   '["What makes a good photograph?"]'::jsonb,
   ARRAY['creativity', 'digital_literacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('a4c83df1-d106-424b-9c46-b410bda09cc0', 1, 'Installation Art', 
   '["Create site-specific artworks", "Use space creatively", "Engage viewers with art"]'::jsonb,
   '["What is installation art?"]'::jsonb,
   ARRAY['creativity', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('a4c83df1-d106-424b-9c46-b410bda09cc0', 2, 'Art Exhibition and Portfolio', 
   '["Prepare artworks for exhibition", "Create an art portfolio", "Present and discuss artworks"]'::jsonb,
   '["How do artists share their work?"]'::jsonb,
   ARRAY['communication', 'self_efficacy']::cbc_competency[],
   ARRAY['integrity', 'love']::cbc_value[], 6),

  -- CRE Grade 7
  ('d30f7d1d-08c1-49c0-bbea-854e32b90bec', 1, 'Old Testament Studies', 
   '["Explore major Old Testament narratives", "Identify key prophets and their messages", "Apply Old Testament teachings to modern life"]'::jsonb,
   '["What can we learn from the Old Testament?"]'::jsonb,
   ARRAY['learning_to_learn', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 6),
  ('d30f7d1d-08c1-49c0-bbea-854e32b90bec', 2, 'New Testament Studies', 
   '["Study the life and teachings of Jesus", "Explore the early Church", "Apply Gospel teachings"]'::jsonb,
   '["How did Jesus teach us to live?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['love', 'respect']::cbc_value[], 6),
  ('42876335-4efa-4ec8-872a-0691654d0e2a', 1, 'Christian Ethics', 
   '["Explore Christian moral principles", "Apply ethics to daily decisions", "Discuss contemporary moral issues"]'::jsonb,
   '["How do Christians make moral decisions?"]'::jsonb,
   ARRAY['critical_thinking', 'citizenship']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 5),
  ('42876335-4efa-4ec8-872a-0691654d0e2a', 2, 'Service and Stewardship', 
   '["Understand Christian service", "Practice stewardship of resources", "Engage in community service"]'::jsonb,
   '["How can Christians serve others?"]'::jsonb,
   ARRAY['citizenship', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'responsibility']::cbc_value[], 5),
  ('e26e8511-f5ee-490e-af20-28d3cd843815', 1, 'Church History', 
   '["Trace the development of the Church", "Identify key figures in Church history", "Appreciate Christian heritage"]'::jsonb,
   '["How did the Church develop?"]'::jsonb,
   ARRAY['learning_to_learn', 'critical_thinking']::cbc_competency[],
   ARRAY['patriotism', 'unity']::cbc_value[], 5),
  ('e26e8511-f5ee-490e-af20-28d3cd843815', 2, 'Ecumenism', 
   '["Understand different Christian denominations", "Promote unity among Christians", "Respect religious diversity"]'::jsonb,
   '["How can Christians work together?"]'::jsonb,
   ARRAY['communication', 'citizenship']::cbc_competency[],
   ARRAY['unity', 'peace']::cbc_value[], 5),

  -- CRE Grade 8
  ('4b2dcd75-a0c4-420d-b057-4cdb76b14f1d', 1, 'Prophetic Books', 
   '["Study major and minor prophets", "Understand prophetic messages", "Apply prophetic teachings today"]'::jsonb,
   '["What did the prophets teach?"]'::jsonb,
   ARRAY['learning_to_learn', 'critical_thinking']::cbc_competency[],
   ARRAY['integrity', 'peace']::cbc_value[], 6),
  ('4b2dcd75-a0c4-420d-b057-4cdb76b14f1d', 2, 'Wisdom Literature', 
   '["Explore Psalms, Proverbs, and Wisdom books", "Apply wisdom teachings", "Appreciate poetic expressions"]'::jsonb,
   '["What wisdom does the Bible offer?"]'::jsonb,
   ARRAY['learning_to_learn', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('c5e09e8f-bdb1-41c0-8daf-043a0d1ccb06', 1, 'Social Justice', 
   '["Understand Christian teaching on justice", "Identify social justice issues", "Take action for justice"]'::jsonb,
   '["How should Christians respond to injustice?"]'::jsonb,
   ARRAY['citizenship', 'critical_thinking']::cbc_competency[],
   ARRAY['social_justice', 'love']::cbc_value[], 6),
  ('c5e09e8f-bdb1-41c0-8daf-043a0d1ccb06', 2, 'Environmental Stewardship', 
   '["Explore Christian responsibility for creation", "Practice environmental care", "Advocate for the environment"]'::jsonb,
   '["How should Christians care for creation?"]'::jsonb,
   ARRAY['citizenship', 'self_efficacy']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 5),
  ('7084f513-9e87-4c36-b69e-c7dd6a49b494', 1, 'Christianity in Africa', 
   '["Trace Christianity in Africa", "Appreciate African Christian contributions", "Understand contextualization"]'::jsonb,
   '["How did Christianity spread in Africa?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['patriotism', 'unity']::cbc_value[], 5),
  ('7084f513-9e87-4c36-b69e-c7dd6a49b494', 2, 'Interfaith Relations', 
   '["Understand world religions", "Practice interfaith dialogue", "Promote religious tolerance"]'::jsonb,
   '["How can different faiths coexist?"]'::jsonb,
   ARRAY['communication', 'citizenship']::cbc_competency[],
   ARRAY['peace', 'respect']::cbc_value[], 5),

  -- CRE Grade 9
  ('d559549f-c064-4099-8254-f792f2151e7b', 1, 'Biblical Interpretation', 
   '["Apply hermeneutical principles", "Interpret Scripture in context", "Apply biblical teachings"]'::jsonb,
   '["How do we interpret the Bible correctly?"]'::jsonb,
   ARRAY['critical_thinking', 'learning_to_learn']::cbc_competency[],
   ARRAY['integrity', 'love']::cbc_value[], 6),
  ('d559549f-c064-4099-8254-f792f2151e7b', 2, 'Pauline Letters', 
   '["Study Paul''s epistles", "Understand theological concepts", "Apply teachings to church life"]'::jsonb,
   '["What did Paul teach the early Church?"]'::jsonb,
   ARRAY['learning_to_learn', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'unity']::cbc_value[], 5),
  ('335cc1b4-ed15-4aff-b621-26e7563c1813', 1, 'Contemporary Christian Issues', 
   '["Discuss current ethical challenges", "Apply Christian principles to modern issues", "Develop moral reasoning"]'::jsonb,
   '["How does Christianity address modern challenges?"]'::jsonb,
   ARRAY['critical_thinking', 'communication']::cbc_competency[],
   ARRAY['integrity', 'social_justice']::cbc_value[], 6),
  ('335cc1b4-ed15-4aff-b621-26e7563c1813', 2, 'Vocation and Ministry', 
   '["Explore Christian calling", "Identify spiritual gifts", "Prepare for Christian service"]'::jsonb,
   '["What is my calling as a Christian?"]'::jsonb,
   ARRAY['self_efficacy', 'citizenship']::cbc_competency[],
   ARRAY['love', 'responsibility']::cbc_value[], 5),
  ('760d70a0-2fe1-4989-a322-5aee7821a38d', 1, 'Global Christianity', 
   '["Explore Christianity worldwide", "Understand mission and evangelism", "Appreciate cultural expressions of faith"]'::jsonb,
   '["How is Christianity expressed globally?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['unity', 'peace']::cbc_value[], 5),
  ('760d70a0-2fe1-4989-a322-5aee7821a38d', 2, 'Christian Leadership', 
   '["Develop leadership skills", "Practice servant leadership", "Lead with integrity"]'::jsonb,
   '["What makes a good Christian leader?"]'::jsonb,
   ARRAY['self_efficacy', 'communication']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 5);