-- Add sub-strands for IRE Grade 9, MUSIC Grade 7-9, PE Grade 7-9 with CORRECT strand IDs

INSERT INTO cbc_sub_strands (strand_id, sub_strand_number, name, specific_learning_outcomes, key_inquiry_questions, core_competencies, values, suggested_lesson_count)
VALUES
  -- IRE Grade 9 (actual IDs)
  ('929b15b0-5f61-4efd-aa3f-2de954f7dfbd', 1, 'Comparative Tafsir', 
   '["Compare different Tafsir approaches", "Analyze scholarly interpretations", "Apply interpretive methods"]'::jsonb,
   '["How do scholars interpret the Quran?"]'::jsonb,
   ARRAY['critical_thinking', 'learning_to_learn']::cbc_competency[],
   ARRAY['integrity', 'love']::cbc_value[], 6),
  ('929b15b0-5f61-4efd-aa3f-2de954f7dfbd', 2, 'Quran and Contemporary Issues', 
   '["Apply Quran to modern challenges", "Discuss contemporary interpretations", "Develop critical analysis"]'::jsonb,
   '["How does the Quran address modern issues?"]'::jsonb,
   ARRAY['critical_thinking', 'communication']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 5),
  ('707b76fe-2023-4c86-af59-2c884a3e1f33', 1, 'Lives of Companions', 
   '["Study biographies of Sahabah", "Extract lessons from their lives", "Emulate their character"]'::jsonb,
   '["What can we learn from the Companions?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('707b76fe-2023-4c86-af59-2c884a3e1f33', 2, 'Islamic History', 
   '["Study early Islamic civilization", "Understand Islamic contributions", "Appreciate Islamic heritage"]'::jsonb,
   '["What did Islamic civilization contribute?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['patriotism', 'unity']::cbc_value[], 6),
  ('1285f578-b8bb-48d0-9c42-63bf024e78b2', 1, 'Islamic Jurisprudence', 
   '["Understand sources of Islamic law", "Explain Fiqh principles", "Apply legal reasoning"]'::jsonb,
   '["How is Islamic law derived?"]'::jsonb,
   ARRAY['critical_thinking', 'learning_to_learn']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 6),
  ('1285f578-b8bb-48d0-9c42-63bf024e78b2', 2, 'Muslims in Contemporary World', 
   '["Discuss challenges facing Muslims", "Promote peaceful coexistence", "Engage in interfaith dialogue"]'::jsonb,
   '["How should Muslims engage with the world?"]'::jsonb,
   ARRAY['communication', 'citizenship']::cbc_competency[],
   ARRAY['peace', 'respect']::cbc_value[], 5),

  -- MUSIC Grade 7
  ('b2fcf4f4-94a8-4d4a-8edd-04df635f3d4c', 1, 'Vocal Techniques', 
   '["Apply proper breathing techniques", "Develop vocal range", "Perform songs with expression"]'::jsonb,
   '["How do we sing effectively?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 6),
  ('b2fcf4f4-94a8-4d4a-8edd-04df635f3d4c', 2, 'Instrumental Skills', 
   '["Play basic instruments", "Read simple notation", "Perform in ensembles"]'::jsonb,
   '["How do we play musical instruments?"]'::jsonb,
   ARRAY['learning_to_learn', 'creativity']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 6),
  ('8bb645e2-78c9-4d44-81b0-4fe5ad97d225', 1, 'Basic Composition', 
   '["Create simple melodies", "Write rhythmic patterns", "Compose short pieces"]'::jsonb,
   '["How do composers create music?"]'::jsonb,
   ARRAY['creativity', 'critical_thinking']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('8bb645e2-78c9-4d44-81b0-4fe5ad97d225', 2, 'Arranging Music', 
   '["Arrange songs for different groups", "Adapt music for instruments", "Create harmonies"]'::jsonb,
   '["How do we arrange music for performance?"]'::jsonb,
   ARRAY['creativity', 'learning_to_learn']::cbc_competency[],
   ARRAY['love', 'responsibility']::cbc_value[], 5),
  ('e7a2d427-142a-4849-b8dd-6619940c6115', 1, 'Music Appreciation', 
   '["Analyze musical works", "Identify musical elements", "Appreciate diverse genres"]'::jsonb,
   '["What makes music meaningful?"]'::jsonb,
   ARRAY['critical_thinking', 'learning_to_learn']::cbc_competency[],
   ARRAY['love', 'patriotism']::cbc_value[], 5),
  ('e7a2d427-142a-4849-b8dd-6619940c6115', 2, 'Music and Culture', 
   '["Explore traditional music", "Understand music in society", "Value cultural music heritage"]'::jsonb,
   '["How does music reflect culture?"]'::jsonb,
   ARRAY['citizenship', 'learning_to_learn']::cbc_competency[],
   ARRAY['patriotism', 'unity']::cbc_value[], 5),

  -- MUSIC Grade 8
  ('db3c57de-77e4-4d0d-a2bd-6d80aada3ba5', 1, 'Advanced Vocal Performance', 
   '["Perform in multiple parts", "Express musical interpretation", "Master dynamics and phrasing"]'::jsonb,
   '["How do vocalists express emotion?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 6),
  ('db3c57de-77e4-4d0d-a2bd-6d80aada3ba5', 2, 'Choral Music', 
   '["Participate in choir", "Blend voices effectively", "Perform choral repertoire"]'::jsonb,
   '["What makes a choir sound unified?"]'::jsonb,
   ARRAY['communication', 'creativity']::cbc_competency[],
   ARRAY['unity', 'love']::cbc_value[], 5),
  ('c564a0d4-bb9b-488e-8565-08b6fd594bf6', 1, 'Music Technology', 
   '["Use music software", "Create digital recordings", "Edit audio tracks"]'::jsonb,
   '["How is technology used in music?"]'::jsonb,
   ARRAY['digital_literacy', 'creativity']::cbc_competency[],
   ARRAY['love', 'responsibility']::cbc_value[], 6),
  ('c564a0d4-bb9b-488e-8565-08b6fd594bf6', 2, 'Songwriting', 
   '["Write lyrics", "Compose original songs", "Structure song forms"]'::jsonb,
   '["How do we write songs?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('d5393fbc-6bdb-4c81-a791-77e47f419d9c', 1, 'World Music', 
   '["Explore global music traditions", "Compare musical systems", "Perform world music"]'::jsonb,
   '["What music exists around the world?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['unity', 'peace']::cbc_value[], 5),
  ('d5393fbc-6bdb-4c81-a791-77e47f419d9c', 2, 'East African Music', 
   '["Study East African music traditions", "Perform regional songs", "Preserve musical heritage"]'::jsonb,
   '["What defines East African music?"]'::jsonb,
   ARRAY['citizenship', 'learning_to_learn']::cbc_competency[],
   ARRAY['patriotism', 'unity']::cbc_value[], 5),

  -- MUSIC Grade 9
  ('bdb9d7f9-d3c1-42f6-96e6-77b9dc630ced', 1, 'Music Performance', 
   '["Prepare for public performance", "Develop stage presence", "Handle performance anxiety"]'::jsonb,
   '["How do we perform confidently?"]'::jsonb,
   ARRAY['self_efficacy', 'communication']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 6),
  ('bdb9d7f9-d3c1-42f6-96e6-77b9dc630ced', 2, 'Ensemble Leadership', 
   '["Lead musical groups", "Conduct basic patterns", "Organize rehearsals"]'::jsonb,
   '["What makes a good music leader?"]'::jsonb,
   ARRAY['communication', 'self_efficacy']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 5),
  ('68344fe2-99ba-410d-8846-f95078443d2a', 1, 'Music Production', 
   '["Produce music tracks", "Mix and master audio", "Create professional recordings"]'::jsonb,
   '["How is recorded music produced?"]'::jsonb,
   ARRAY['digital_literacy', 'creativity']::cbc_competency[],
   ARRAY['love', 'responsibility']::cbc_value[], 6),
  ('68344fe2-99ba-410d-8846-f95078443d2a', 2, 'Film and Media Music', 
   '["Understand music in media", "Create music for video", "Analyze soundtrack techniques"]'::jsonb,
   '["How does music enhance media?"]'::jsonb,
   ARRAY['creativity', 'digital_literacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('f7e11f6c-1ec5-4531-b2c5-d2b4bde5263b', 1, 'Music Careers', 
   '["Explore music career paths", "Develop entrepreneurship", "Build a music portfolio"]'::jsonb,
   '["What careers exist in music?"]'::jsonb,
   ARRAY['self_efficacy', 'communication']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 5),
  ('f7e11f6c-1ec5-4531-b2c5-d2b4bde5263b', 2, 'Music and Community', 
   '["Use music for social impact", "Organize music events", "Serve community through music"]'::jsonb,
   '["How can music serve the community?"]'::jsonb,
   ARRAY['citizenship', 'communication']::cbc_competency[],
   ARRAY['love', 'unity']::cbc_value[], 5),

  -- PE Grade 7
  ('0beb5e5c-9a68-4734-8c03-9c7fc081f8ab', 1, 'Advanced Movement Skills', 
   '["Perform complex movement patterns", "Apply biomechanics principles", "Develop coordination"]'::jsonb,
   '["How do we improve movement efficiency?"]'::jsonb,
   ARRAY['self_efficacy', 'learning_to_learn']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 6),
  ('0beb5e5c-9a68-4734-8c03-9c7fc081f8ab', 2, 'Dance and Choreography', 
   '["Perform various dance styles", "Create choreography", "Express through movement"]'::jsonb,
   '["How do we create dance performances?"]'::jsonb,
   ARRAY['creativity', 'communication']::cbc_competency[],
   ARRAY['love', 'patriotism']::cbc_value[], 5),
  ('0a6eb7a9-7be7-44f7-ad64-208ca124e6bb', 1, 'Fitness Training', 
   '["Develop fitness programs", "Apply training principles", "Monitor fitness progress"]'::jsonb,
   '["How do we improve physical fitness?"]'::jsonb,
   ARRAY['self_efficacy', 'learning_to_learn']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 6),
  ('0a6eb7a9-7be7-44f7-ad64-208ca124e6bb', 2, 'Health and Wellness', 
   '["Practice healthy lifestyle", "Understand nutrition for sports", "Manage stress through exercise"]'::jsonb,
   '["How does exercise improve health?"]'::jsonb,
   ARRAY['learning_to_learn', 'self_efficacy']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 5),
  ('ac82ff11-f5a3-4988-bfb8-f3837f630282', 1, 'Team Sports', 
   '["Play team games effectively", "Apply tactics and strategies", "Demonstrate sportsmanship"]'::jsonb,
   '["What makes a good team player?"]'::jsonb,
   ARRAY['communication', 'citizenship']::cbc_competency[],
   ARRAY['unity', 'respect']::cbc_value[], 6),
  ('ac82ff11-f5a3-4988-bfb8-f3837f630282', 2, 'Individual Sports', 
   '["Develop individual sport skills", "Set personal goals", "Compete fairly"]'::jsonb,
   '["How do we excel in individual sports?"]'::jsonb,
   ARRAY['self_efficacy', 'learning_to_learn']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 5),

  -- PE Grade 8
  ('64fb5010-5a4c-496c-91d1-ef1a1d656aa2', 1, 'Sports Science Basics', 
   '["Understand body systems", "Apply physiology to sports", "Prevent sports injuries"]'::jsonb,
   '["How does the body respond to exercise?"]'::jsonb,
   ARRAY['learning_to_learn', 'critical_thinking']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 6),
  ('64fb5010-5a4c-496c-91d1-ef1a1d656aa2', 2, 'Movement Analysis', 
   '["Analyze sporting techniques", "Provide feedback", "Improve performance"]'::jsonb,
   '["How can we improve sporting techniques?"]'::jsonb,
   ARRAY['critical_thinking', 'learning_to_learn']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 5),
  ('98804379-4b0f-4aaf-ae20-bbd752b2958d', 1, 'Specialized Training', 
   '["Apply sport-specific training", "Develop athletic qualities", "Peak for competition"]'::jsonb,
   '["How do athletes train for competition?"]'::jsonb,
   ARRAY['self_efficacy', 'learning_to_learn']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 6),
  ('98804379-4b0f-4aaf-ae20-bbd752b2958d', 2, 'Recovery and Regeneration', 
   '["Practice recovery techniques", "Understand rest importance", "Prevent overtraining"]'::jsonb,
   '["Why is recovery important in sports?"]'::jsonb,
   ARRAY['learning_to_learn', 'self_efficacy']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 4),
  ('6878c42f-2724-481a-92b9-84355d9e0b7c', 1, 'Advanced Team Sports', 
   '["Apply advanced tactics", "Lead teams effectively", "Organize tournaments"]'::jsonb,
   '["What strategies win games?"]'::jsonb,
   ARRAY['communication', 'critical_thinking']::cbc_competency[],
   ARRAY['unity', 'respect']::cbc_value[], 6),
  ('6878c42f-2724-481a-92b9-84355d9e0b7c', 2, 'Sports Leadership', 
   '["Develop leadership skills", "Coach peers", "Organize sports activities"]'::jsonb,
   '["What makes a good sports leader?"]'::jsonb,
   ARRAY['self_efficacy', 'communication']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 5),

  -- PE Grade 9
  ('2a641745-b03d-4d9e-94d5-bf8679045b8a', 1, 'Performance Enhancement', 
   '["Optimize athletic performance", "Apply sports psychology", "Develop mental toughness"]'::jsonb,
   '["How do athletes reach peak performance?"]'::jsonb,
   ARRAY['self_efficacy', 'critical_thinking']::cbc_competency[],
   ARRAY['integrity', 'responsibility']::cbc_value[], 6),
  ('2a641745-b03d-4d9e-94d5-bf8679045b8a', 2, 'Creative Movement', 
   '["Design movement sequences", "Express through physical performance", "Create sports presentations"]'::jsonb,
   '["How can movement be creative?"]'::jsonb,
   ARRAY['creativity', 'self_efficacy']::cbc_competency[],
   ARRAY['love', 'integrity']::cbc_value[], 5),
  ('e815b9dd-240b-4608-b876-43c0122e5f3a', 1, 'Sports Nutrition', 
   '["Plan athletic diets", "Understand supplements", "Hydrate properly for sports"]'::jsonb,
   '["What should athletes eat?"]'::jsonb,
   ARRAY['learning_to_learn', 'self_efficacy']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 5),
  ('e815b9dd-240b-4608-b876-43c0122e5f3a', 2, 'Injury Prevention and First Aid', 
   '["Prevent common injuries", "Apply first aid", "Rehabilitate from injuries"]'::jsonb,
   '["How do we prevent and treat sports injuries?"]'::jsonb,
   ARRAY['learning_to_learn', 'citizenship']::cbc_competency[],
   ARRAY['responsibility', 'love']::cbc_value[], 5),
  ('458416a0-581e-482e-b39f-f39046303cba', 1, 'Sports Event Management', 
   '["Plan sports events", "Officiate games", "Manage sports facilities"]'::jsonb,
   '["How are sports events organized?"]'::jsonb,
   ARRAY['communication', 'self_efficacy']::cbc_competency[],
   ARRAY['responsibility', 'integrity']::cbc_value[], 5),
  ('458416a0-581e-482e-b39f-f39046303cba', 2, 'Sports and Society', 
   '["Understand sports in community", "Promote inclusive sports", "Address issues in sports"]'::jsonb,
   '["What role does sports play in society?"]'::jsonb,
   ARRAY['citizenship', 'communication']::cbc_competency[],
   ARRAY['unity', 'social_justice']::cbc_value[], 5);